//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotaAnalyst {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotaAnalyst.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить героя.
        /// </summary>
        internal static string AddPhotoPageAddButton {
            get {
                return ResourceManager.GetString("AddPhotoPageAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавления героя.
        /// </summary>
        internal static string AddPhotoPageAddingHero {
            get {
                return ResourceManager.GetString("AddPhotoPageAddingHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ловкость.
        /// </summary>
        internal static string AddPhotoPageAgility {
            get {
                return ResourceManager.GetString("AddPhotoPageAgility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Атрибуты.
        /// </summary>
        internal static string AddPhotoPageAttribute {
            get {
                return ResourceManager.GetString("AddPhotoPageAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интеллект.
        /// </summary>
        internal static string AddPhotoPageIntelligence {
            get {
                return ResourceManager.GetString("AddPhotoPageIntelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать фото.
        /// </summary>
        internal static string AddPhotoPagePhotoButton {
            get {
                return ResourceManager.GetString("AddPhotoPagePhotoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сила.
        /// </summary>
        internal static string AddPhotoPageStrength {
            get {
                return ResourceManager.GetString("AddPhotoPageStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Герой успешно добавлен.
        /// </summary>
        internal static string AddPhotoPageSucces {
            get {
                return ResourceManager.GetString("AddPhotoPageSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось добавить героя.
        /// </summary>
        internal static string AddPhotoPageUnSucces {
            get {
                return ResourceManager.GetString("AddPhotoPageUnSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справочник.
        /// </summary>
        internal static string MainPageBookButton {
            get {
                return ResourceManager.GetString("MainPageBookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать своего героя.
        /// </summary>
        internal static string MainPageCreateButton {
            get {
                return ResourceManager.GetString("MainPageCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пикер.
        /// </summary>
        internal static string MainPagePickerButton {
            get {
                return ResourceManager.GetString("MainPagePickerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статистика.
        /// </summary>
        internal static string MainPageStatsButton {
            get {
                return ResourceManager.GetString("MainPageStatsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите сторону.
        /// </summary>
        internal static string PickChoicePageChoiceLabel {
            get {
                return ResourceManager.GetString("PickChoicePageChoiceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тьма.
        /// </summary>
        internal static string PickChoicePageDireButton {
            get {
                return ResourceManager.GetString("PickChoicePageDireButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Первый пик.
        /// </summary>
        internal static string PickChoicePageFirstPickLabel {
            get {
                return ResourceManager.GetString("PickChoicePageFirstPickLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти к стадии пика.
        /// </summary>
        internal static string PickChoicePageGoToPickButton {
            get {
                return ResourceManager.GetString("PickChoicePageGoToPickButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Симулятор Capitans Mode.
        /// </summary>
        internal static string PickChoicePageName {
            get {
                return ResourceManager.GetString("PickChoicePageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соперник.
        /// </summary>
        internal static string PickChoicePageOpponentPicked {
            get {
                return ResourceManager.GetString("PickChoicePageOpponentPicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свет.
        /// </summary>
        internal static string PickChoicePageRadiantButton {
            get {
                return ResourceManager.GetString("PickChoicePageRadiantButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы.
        /// </summary>
        internal static string PickChoicePageYouPicked {
            get {
                return ResourceManager.GetString("PickChoicePageYouPicked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анимация.
        /// </summary>
        internal static string SettingsAnimation {
            get {
                return ResourceManager.GetString("SettingsAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анимация при переходе.
        /// </summary>
        internal static string SettingsAnimationOnGoing {
            get {
                return ResourceManager.GetString("SettingsAnimationOnGoing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Анимация перехода.
        /// </summary>
        internal static string SettingsAnimationTime {
            get {
                return ResourceManager.GetString("SettingsAnimationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить иконку анимации.
        /// </summary>
        internal static string SettingsChangeAnimation {
            get {
                return ResourceManager.GetString("SettingsChangeAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сек..
        /// </summary>
        internal static string SettingsSeconds {
            get {
                return ResourceManager.GetString("SettingsSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string SettingsSettings {
            get {
                return ResourceManager.GetString("SettingsSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Про игры.
        /// </summary>
        internal static string StatsPageProButton {
            get {
                return ResourceManager.GetString("StatsPageProButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паб игры.
        /// </summary>
        internal static string StatsPagePubButton {
            get {
                return ResourceManager.GetString("StatsPagePubButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Винрейт в про играх.
        /// </summary>
        internal static string WinratePageWinrateProLabel {
            get {
                return ResourceManager.GetString("WinratePageWinrateProLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Винрейт в пабе.
        /// </summary>
        internal static string WinratePageWinratePubLabel {
            get {
                return ResourceManager.GetString("WinratePageWinratePubLabel", resourceCulture);
            }
        }
    }
}
